management:
  endpoints:
    enabled-by-default: true
    health:
      show-details: always
    web:
      exposure:
        include: '*'
server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/migagi/io.springkubed.config.git
